### PR TITLE
couple of Goldens

### PR DESCRIPTION
**Pull request by abdushakoor12**

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
Hi @abdushakoor12 this one just needs a 

`dart format lib test` 

on the example project I'd say

**Comment by MelbourneDeveloper** [comment]
Thanks @abdushakoor12 . Had to bring through a temp branch again here: https://github.com/Nimblesite/nimble_charts/pull/41/files

**Comment by MelbourneDeveloper** [comment]
@abdushakoor12 I added you to the repo so you should be able to create branches in this repo now without the fork.

Please prefix new branches with abdushakoor12/[branchname] so I can keep track. Thankyou!

**Comment by abdushakoor12** [comment]
Ok thanks @MelbourneDeveloper

**Pull request merged**
